name: ⁉️ Discussion
description: Want to discuss something? Use this template
labels: [discussion]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this discussion report!
  - type: textarea
    id: discussion-description
    attributes:
      label: Discussion
      description: 'Explain the matter here!'
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/carloscuesta/gitmoji/blob/master/CODE_OF_CONDUCT.md)
          required: true
        - label: Read the [Contributing Guide](https://github.com/carloscuesta/gitmoji/blob/master/.github/CONTRIBUTING.md).
          required: true
        - label: Check that there isn't already an issue requesting the same feature.
          required: true
