name: NPM Publish
on:
  push:
    tags:
      - "v*"
permissions:
  id-token: write
  contents: write
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v6
        with:
          cache: "pnpm"
          node-version-file: ".node-version"
      - name: Install dependencies 📦
        run: pnpm install
      - name: Build 👷‍♂️
        run: pnpm turbo run build --filter=gitmojis
      - name: Publish package to NPM 🚀
        run: pnpm turbo publishPackage
      - name: Publish GitHub Release 📝
        uses: softprops/action-gh-release@v3
        with:
          name: gitmoji ${{github.ref_name}}
          generate_release_notes: true
